### ISSUE TITLE
Bug: Dimmed text color in Dark theme does not match rest of bar

### ISSUE THREAD

**Issue by Sergio-Mira** [leits/MeetingBar#474]
**App version**
Current version (4.0.5)

**Describe the bug**
When the screen is not active all the bar icons and text are dimmed. However, the dimmed color of text in Meeting Bar is less readable and does not match the rest.

It was fixed in a release (https://github.com/leits/MeetingBar/issues/314) but it has since been reverted it seems:
https://github.com/leits/MeetingBar/pull/436/files
https://github.com/leits/MeetingBar/blame/master/MeetingBar/StatusBarItemController.swift#L238

**To Reproduce**
1. Setup 2 screens
2. Set Dark theme in MacOS
3. Click in one of the monitors
EXPECTED: Dimmed text color in the other monitor matches the rest of the bar

**Screenshots**
![Screenshot 2021-08-17 at 09 40 52](https://user-images.githubusercontent.com/2519238/129692916-d653d57b-0637-44fc-a7f1-d4739f6952ff.png)

**Desktop:**
 - macOS version: 12.4

**Comment by leits** [comment]
Hi @Sergio-Mira,
Can you check the latest version? 

Can't reproduce this issue anymore. So I assume it was fixed in one of the last releases.
I'll close the issue but feel free to reopen it.

**Comment by Sergio-Mira** [comment]
Its still happening unfortunately, and I'm not able to re-open this issue. Will I open a new one? Thanks!

**Comment by leits** [comment]
Can I ask you to try again with the latest 4.2?

**Comment by Sergio-Mira** [comment]
Still happening with 4.2:
![Screenshot 2022-10-27 at 16 58 24](https://user-images.githubusercontent.com/2519238/198326350-80cc6434-a2a2-4d80-98a7-d2d42074b8c0.png)

**Comment by leits** [comment]
Damn, thanks for pointing again, I'll dig into this issue.

**Comment by Sergio-Mira** [comment]
That line to set it to white was the fix I think and it then got removed probably because it caused some other issue

**Comment by leits** [comment]
Can't reproduce it :( 
![image](https://user-images.githubusercontent.com/12017826/198389616-ef5af4aa-7f1f-4144-9a98-5fd13484d4d5.png)

Are you using "show under title" option for the time appereance?

**Comment by leits** [comment]
Hardcoding `styles[NSAttributedString.Key.foregroundColor] = NSColor.white` prevents Apple from changing the appearance of the text based on the background. So white text will always be white with this setting, even when all other icons will become dark to contrast with the background.

Right now, the text color is changing only by Apple, and no matter how hard I try to reproduce this issue text always has the correct color. Are you sure you use the latest version?

The only exception is the old logic for "show under title" option for the time appearance that is available only for macOS Catalina.

**Comment by Sergio-Mira** [comment]
These are my appaerance options in the app:
![Screenshot 2022-10-28 at 14 37 03](https://user-images.githubusercontent.com/2519238/198588508-e28fb466-666a-4c47-935d-ecaa2feab446.png)

MacOS version is `12.6.1 (21G217) - Monterrey`

**Comment by Sergio-Mira** [comment]
It could have been that the defaults of the app were newer than the OS. It looks like the date time now has a similar (too dark imo) text when its not the active screen. Cosing this issue, thanks!

<img width="652" alt="Screenshot 2022-11-07 at 10 03 18" src="https://user-images.githubusercontent.com/2519238/200270110-d8a30470-45a3-4986-875c-d36466e074be.png">
