### ISSUE TITLE
Bug: MeetingBar hangs at launch or shortly

### ISSUE THREAD

**Issue by 537m3** [leits/MeetingBar#796]
### macOS version

15.3 (24D60)

### MeetingBar version

4.10.0

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

Has been working flawlessly for over a year. About a week ago it started hanging, usually right on launch, but occasionally after running for a short period of time (has run for over 30 mins once since the symptoms began, but lately hangs immediately at launch before even displaying any upcoming meetings in the right menubar location. The icon itself does display, and I get the spinning pinwheel when I hover over it. Activity Monitor shows it as Not Responding, generally with less than 1s of cumulative CPU time. Continues until I force quit.

I tried rebooting several times and reinstalling the app. Same symptoms.

Unsure if related, but Apple's Single Sign-On app (which is launched automatically, not by me) is also always Not Responding in Activity Monitor and similar very low CPU time before hanging and never recovering. 

Is there any way I can get log output for the app to see what it's doing before it hangs?

### Reproduction steps

1. Launch MeetingBar
2. Notice it is hung and unusable

### Expected behavior

Normal operation

**Comment by virtue3** [comment]
Also seeing the same behavior.  

Can't really do anything since the app immediately crashes off the menu bar.

I tried switching from google calendar to mac calendar and same behavior.

**Comment by danieldisu** [comment]
Happening to me too

I started seeing it on 15.3.1

**Comment by wolvgrad98** [comment]
Also happening in MacOS 15.3.2.

**Comment by bzenker-amplify** [comment]
> Can't really do anything since the app immediately crashes off the menu bar.

I wonder if this deserves it's own issue as the OP doesn't have this behavior, but personally this is the behavior on my side. The app is **not** hanging, but it does **not** display on the Apple menu bar.

**Comment by cesarferradas** [comment]
Can confirm this started happening since MacOS 15.1 for me too.

**Comment by leits** [comment]
Hi folks,
Thanks again for reporting this performance issue. I’ve just published a 4.11 beta release with a number of under-the-hood performance optimizations in MeetingBar. You can grab it here:
https://github.com/leits/MeetingBar/releases/tag/v4.11.beta 

Once you’ve had a chance to try it, could you please let me know whether you still see the issues? Any logs, profiled timings, or specific repro steps you can share will be super helpful. Thanks!

**Comment by glenjamin** [comment]
I've just tried switching to the beta, but I'm still getting a crash on startup. This is the crash report from `Console`

<details>

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               MeetingBar [73441]
Path:                  /Applications/MeetingBar.app/Contents/MacOS/MeetingBar
Identifier:            leits.MeetingBar
Version:               4.11.0 (163)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-05-19 10:19:01.1144 +0100
OS Version:            macOS 15.4.1 (24E263)
Report Version:        12
Anonymous UUID:        82029A70-DADA-36A8-BDDF-42171CE7A5E5

Sleep/Wake UUID:       701805CA-D36C-4840-9492-20C54E0DFAE7

Time Awake Since Boot: 210000 seconds
Time Since Wake:       3396 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000102dea2b8

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [73441]

Thread 0 Crashed:
0   MeetingBar                    	       0x102dea2b8 0x102d9c000 + 320184
1   MeetingBar                    	       0x102da61e1 0x102d9c000 + 41441
2   MeetingBar                    	       0x102d9fba9 0x102d9c000 + 15273
3   MeetingBar                    	       0x102e42939 0x102d9c000 + 682297
4   MeetingBar                    	       0x102d9fba9 0x102d9c000 + 15273
5   libswift_Concurrency.dylib    	       0x281c1a83d completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 1:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0

Thread 7:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x198dd7c34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x198dea308 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x198de0764 mach_msg_overwrite + 484
3   libsystem_kernel.dylib        	       0x198dd7fa8 mach_msg + 24
4   CoreFoundation                	       0x198f04f8c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x198f038a8 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x198f02d68 CFRunLoopRunSpecific + 572
7   AppKit                        	       0x19cc79818 _NSEventThread + 140
8   libsystem_pthread.dylib       	       0x198e19c0c _pthread_start + 136
9   libsystem_pthread.dylib       	       0x198e14b80 thread_start + 8

Thread 8:
0   libsystem_pthread.dylib       	       0x198e14b6c start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600002b9a100   x1: 0x0000000102f435e8   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x000000016d061258   x6: 0x0000000000000001   x7: 0x000000016d061248
    x8: 0x0000000000000010   x9: 0x0000000000000008  x10: 0x00000000a0080001  x11: 0x0200000102f435ed
   x12: 0x0000000000000006  x13: 0x000000015783e050  x14: 0x0900600001aaa4c7  x15: 0x0000600001aaa4c0
   x16: 0x0000000102f435e8  x17: 0x0000000102f435e8  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000600002b9a100  x21: 0x0000600003094480  x22: 0x00000001558094d0  x23: 0x0000000102f5d000
   x24: 0x0000000000000012  x25: 0x0000000207cecd60  x26: 0x0000000000000000  x27: 0x00000000211200d9
   x28: 0xffffffff76ffffff   fp: 0x000000016d061ea0   lr: 0x0000000102dea1f4
    sp: 0x000000016d061e80   pc: 0x0000000102dea2b8 cpsr: 0x60000000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102d9c000 -        0x102f27fff leits.MeetingBar (4.11.0) <40c6591a-0f3b-3940-b274-addcc1dc3df0> /Applications/MeetingBar.app/Contents/MacOS/MeetingBar
       0x103358000 -        0x103363fff libobjc-trampolines.dylib (*) <fb6f2685-3c65-37ec-8ee3-8adba6e1995f> /usr/lib/libobjc-trampolines.dylib
       0x110e00000 -        0x111533fff com.apple.AGXMetalG16G-B0 (325.34.1) <49b761de-e87f-38d4-b771-a13b891d48a9> /System/Library/Extensions/AGXMetalG16G_B0.bundle/Contents/MacOS/AGXMetalG16G_B0
       0x281bb5000 -        0x281c354fb libswift_Concurrency.dylib (*) <fa0745db-7869-362e-bef5-066f6f1c5459> /usr/lib/swift/libswift_Concurrency.dylib
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x198e13000 -        0x198e1fa47 libsystem_pthread.dylib (*) <8d27ec9a-d919-31a4-8df8-31a2fd2e593c> /usr/lib/system/libsystem_pthread.dylib
       0x198dd7000 -        0x198e1230b libsystem_kernel.dylib (*) <225cb279-20a9-381d-a163-d2be263f5327> /usr/lib/system/libsystem_kernel.dylib
       0x198e88000 -        0x1993c6fff com.apple.CoreFoundation (6.9) <39e0f63a-3ab8-39e9-97f8-333cde9a7ba4> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19cb1b000 -        0x19dfabdff com.apple.AppKit (6.9) <1d6df541-4a74-3a0e-8a8f-15aee6f93da9> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)
Writable regions: Total=1.4G written=673K(0%) resident=673K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
CG image                           144K        7 
ColorSync                          544K       28 
CoreAnimation                      576K       33 
CoreGraphics                        32K        2 
CoreUI image data                 2416K       19 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.4G       68 
MALLOC guard page                  384K       24 
STACK GUARD                       56.1M        8 
STACK GUARD (graphics)              16K        1 
Stack                             12.2M        9 
VM_ALLOCATE                        128K        7 
__AUTH                            5328K      682 
__AUTH_CONST                      75.4M      922 
__CTF                               824        1 
__DATA                            25.0M      903 
__DATA_CONST                      26.7M      931 
__DATA_DIRTY                      2762K      337 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       622.4M        4 
__OBJC_RO                         61.3M        1 
__OBJC_RW                         2391K        1 
__TEXT                             1.0G      952 
__TPRO_CONST                       128K        2 
mapped file                      277.4M       35 
page table in kernel               673K        1 
shared memory                     1376K       14 
===========                     =======  ======= 
TOTAL                              3.5G     5001 



-----------
Full Report
-----------

{"app_name":"MeetingBar","timestamp":"2025-05-19 10:19:01.00 +0100","app_version":"4.11.0","slice_uuid":"40c6591a-0f3b-3940-b274-addcc1dc3df0","build_version":"163","platform":1,"bundleID":"leits.MeetingBar","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 15.4.1 (24E263)","roots_installed":0,"name":"MeetingBar","incident_id":"9E1941FA-FFEE-4A9E-BDF9-E88A6A94BE3F"}
{
  "uptime" : 210000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac16,12",
  "coalitionID" : 58625,
  "osVersion" : {
    "train" : "macOS 15.4.1",
    "build" : "24E263",
    "releaseType" : "User"
  },
  "captureTime" : "2025-05-19 10:19:01.1144 +0100",
  "codeSigningMonitor" : 2,
  "incident" : "9E1941FA-FFEE-4A9E-BDF9-E88A6A94BE3F",
  "pid" : 73441,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2025-05-19 10:18:58.7358 +0100",
  "procStartAbsTime" : 5140111439760,
  "procExitAbsTime" : 5140168497931,
  "procName" : "MeetingBar",
  "procPath" : "\/Applications\/MeetingBar.app\/Contents\/MacOS\/MeetingBar",
  "bundleInfo" : {"CFBundleShortVersionString":"4.11.0","CFBundleVersion":"163","CFBundleIdentifier":"leits.MeetingBar"},
  "storeInfo" : {"deviceIdentifierForVendor":"F6ADB4D5-F2B6-539E-9362-6D2746000409","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "leits.MeetingBar",
  "crashReporterKey" : "82029A70-DADA-36A8-BDDF-42171CE7A5E5",
  "appleIntelligenceStatus" : {"state":"available"},
  "codeSigningID" : "leits.MeetingBar",
  "codeSigningTeamID" : "KGH289N6T8",
  "codeSigningFlags" : 570520337,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "codeSigningAuxiliaryInfo" : 0,
  "instructionByteStream" : {"beforePC":"9c9AqfcHQ\/i9+0OSAAAf1sAKANAA4DKRAf\/\/0CFAH5FzrQOUpP\/\/Fw==","atPC":"IAAg1L0DRLLzDx74\/XsBqfYHAPn9QwCR0wJA+bODH\/h0gkap1gJA+Q=="},
  "bootSessionUUID" : "8BEF14F8-01CA-4848-A556-91E7322CD60C",
  "wakeTime" : 3396,
  "sleepWakeUUID" : "701805CA-D36C-4840-9492-20C54E0DFAE7",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000102dea2b8","rawCodes":[1,4343112376],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":73441},
  "os_fault" : {"process":"MeetingBar"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":10163563,"threadState":{"x":[{"value":105553161986304},{"value":4344526312},{"value":0},{"value":0},{"value":0},{"value":6124081752},{"value":1},{"value":6124081736},{"value":16},{"value":8},{"value":2684878849},{"value":144115192420382189},{"value":6},{"value":5763227728},{"value":648623899485578439},{"value":105553144227008},{"value":4344526312},{"value":4344526312},{"value":0},{"value":0},{"value":105553161986304},{"value":105553167205504},{"value":5729457360},{"value":4344631296},{"value":18},{"value":8720928096,"symbolLocation":224,"symbol":"_main_thread"},{"value":0},{"value":554827993},{"value":18446744071411073023}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4343112180},"cpsr":{"value":1610612736},"fp":{"value":6124084896},"sp":{"value":6124084864},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4343112376,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":320184,"imageIndex":0},{"imageOffset":41441,"imageIndex":0},{"imageOffset":15273,"imageIndex":0},{"imageOffset":682297,"imageIndex":0},{"imageOffset":15273,"imageIndex":0},{"imageOffset":415805,"symbol":"completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*)","symbolLocation":1,"imageIndex":3}]},{"id":10163568,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6124646400},{"value":5635},{"value":6124109824},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6124646400},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}},{"id":10163569,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6125219840},{"value":4355},{"value":6124683264},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6125219840},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}},{"id":10163575,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6125793280},{"value":20227},{"value":6125256704},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6125793280},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}},{"id":10163576,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6126366720},{"value":19971},{"value":6125830144},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6126366720},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}},{"id":10163577,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6126940160},{"value":33539},{"value":6126403584},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6126940160},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}},{"id":10163581,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6127513600},{"value":41731},{"value":6126977024},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6127513600},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}},{"id":10163590,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":203422536040448},{"value":0},{"value":203422536040448},{"value":2},{"value":4294967295},{"value":0},{"value":17179869184},{"value":0},{"value":2},{"value":0},{"value":0},{"value":47363},{"value":0},{"value":18446744073709551569},{"value":8738165176},{"value":0},{"value":4294967295},{"value":2},{"value":203422536040448},{"value":0},{"value":203422536040448},{"value":6128083080},{"value":8589934592},{"value":21592279046},{"value":18446744073709550527},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6859694856},"cpsr":{"value":0},"fp":{"value":6128082928},"sp":{"value":6128082848},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6859619380},"far":{"value":0}},"frames":[{"imageOffset":3124,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":78600,"symbol":"mach_msg2_internal","symbolLocation":76,"imageIndex":6},{"imageOffset":38756,"symbol":"mach_msg_overwrite","symbolLocation":484,"imageIndex":6},{"imageOffset":4008,"symbol":"mach_msg","symbolLocation":24,"imageIndex":6},{"imageOffset":511884,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":7},{"imageOffset":506024,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":7},{"imageOffset":503144,"symbol":"CFRunLoopRunSpecific","symbolLocation":572,"imageIndex":7},{"imageOffset":1435672,"symbol":"_NSEventThread","symbolLocation":140,"imageIndex":8},{"imageOffset":27660,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":5},{"imageOffset":7040,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":10163641,"frames":[{"imageOffset":7020,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}],"threadState":{"x":[{"value":6128660480},{"value":0},{"value":6128123904},{"value":0},{"value":278532},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":0},"fp":{"value":0},"sp":{"value":6128660480},"esr":{"value":0,"description":" Address size fault"},"pc":{"value":6859869036},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342792192,
    "CFBundleShortVersionString" : "4.11.0",
    "CFBundleIdentifier" : "leits.MeetingBar",
    "size" : 1622016,
    "uuid" : "40c6591a-0f3b-3940-b274-addcc1dc3df0",
    "path" : "\/Applications\/MeetingBar.app\/Contents\/MacOS\/MeetingBar",
    "name" : "MeetingBar",
    "CFBundleVersion" : "163"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4348805120,
    "size" : 49152,
    "uuid" : "fb6f2685-3c65-37ec-8ee3-8adba6e1995f",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4578082816,
    "CFBundleShortVersionString" : "325.34.1",
    "CFBundleIdentifier" : "com.apple.AGXMetalG16G-B0",
    "size" : 7553024,
    "uuid" : "49b761de-e87f-38d4-b771-a13b891d48a9",
    "path" : "\/System\/Library\/Extensions\/AGXMetalG16G_B0.bundle\/Contents\/MacOS\/AGXMetalG16G_B0",
    "name" : "AGXMetalG16G_B0",
    "CFBundleVersion" : "325.34.1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 10766471168,
    "size" : 525564,
    "uuid" : "fa0745db-7869-362e-bef5-066f6f1c5459",
    "path" : "\/usr\/lib\/swift\/libswift_Concurrency.dylib",
    "name" : "libswift_Concurrency.dylib"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6859862016,
    "size" : 51784,
    "uuid" : "8d27ec9a-d919-31a4-8df8-31a2fd2e593c",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6859616256,
    "size" : 242444,
    "uuid" : "225cb279-20a9-381d-a163-d2be263f5327",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6860341248,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5500928,
    "uuid" : "39e0f63a-3ab8-39e9-97f8-333cde9a7ba4",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "3423"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6923857920,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 21564928,
    "uuid" : "1d6df541-4a74-3a0e-8a8f-15aee6f93da9",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2575.50.27"
  }
],
  "sharedCache" : {
  "base" : 6855229440,
  "size" : 5020123136,
  "uuid" : "bb86a9b4-8362-37b8-b028-212703af6f30"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)\nWritable regions: Total=1.4G written=673K(0%) resident=673K(0%) swapped_out=0K(0%) unallocated=1.4G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nCG image                           144K        7 \nColorSync                          544K       28 \nCoreAnimation                      576K       33 \nCoreGraphics                        32K        2 \nCoreUI image data                 2416K       19 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.4G       68 \nMALLOC guard page                  384K       24 \nSTACK GUARD                       56.1M        8 \nSTACK GUARD (graphics)              16K        1 \nStack                             12.2M        9 \nVM_ALLOCATE                        128K        7 \n__AUTH                            5328K      682 \n__AUTH_CONST                      75.4M      922 \n__CTF                               824        1 \n__DATA                            25.0M      903 \n__DATA_CONST                      26.7M      931 \n__DATA_DIRTY                      2762K      337 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       622.4M        4 \n__OBJC_RO                         61.3M        1 \n__OBJC_RW                         2391K        1 \n__TEXT                             1.0G      952 \n__TPRO_CONST                       128K        2 \nmapped file                      277.4M       35 \npage table in kernel               673K        1 \nshared memory                     1376K       14 \n===========                     =======  ======= \nTOTAL                              3.5G     5001 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "6988963c3dda1ff873a465c9d3141d8426022e2a",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "645197bf528fbf3c3af54105",
      "factorPackIds" : {
        "SIRI_VALUE_INFERENCE_PERVASIVE_ENTITY_RESOLUTION" : "663e65b4a1526e1ca0e288a1"
      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "64c025b28b7f0e739e4fbe58",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_CLASSIC_DEPRECATION" : "657ba0a39ec5da283662e9d2"
      },
      "deploymentId" : 240000040
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "928dfbce-0cc0-4f29-866f-5542e51ad72e",
      "experimentId" : "67f46e2984eaf455d73c609a",
      "deploymentId" : 400000001
    },
    {
      "treatmentId" : "28060e10-d4e5-4163-aa2b-d8bd088d5cbf",
      "experimentId" : "6685b283afc7c17197d69eec",
      "deploymentId" : 400000012
    }
  ]
}
}
```
</details>

**Comment by leits** [comment]
Thanks for reporting. The bug fix has been released!
Feel free to reopen the issue if the error still occurs.
