### ISSUE TITLE
Bug: Meetingbar breaks every day - events not refreshing

### ISSUE THREAD

**Issue by dcc635** [leits/MeetingBar#869]
### macOS version

15.7.1 (24G231)

### MeetingBar version

4.11.6

### Installation source

AppStore

### Calendars provider

Google Calendar

### Bug description

I believe that every day for the last few days, Meetingbar has failed to load the events, and effectively does nothing. When I open the Meetingbar dropdown, it was showing yesterday's events grayed out. I then tried Quick Actions -> Refresh Sources, and that fixed it. I'm hoping that fixed it for good, but I expect it will fail silently again tomorrow and I'll miss a few more meetings. Any ideas?

**Comment by mhasanbulli** [comment]
I am having the same issue actually with Google Calendar, I have to re-authenticate every day. Sometimes during the day, when invites change, those changes are not synced.

**Comment by davidsandilands** [comment]
Just to highlight I had been following this issue as I was experiencing the same but since upgrading to MacOS Tahoe 26.x  4.11.6 has been working perfectly for me

**Comment by grantneale** [comment]
I have the same issue as @mhasanbulli on Sequoia 15.7.2

**Comment by mhasanbulli** [comment]
@grantneale Try reinstalling the app. I overwrote my existing installation, and it started to work again.

**Comment by scottgreenup** [comment]
> I am having the same issue actually with Google Calendar, I have to re-authenticate every day. Sometimes during the day, when invites change, those changes are not synced.

@mhasanbulli / @grantneale — I don't know if this helps, but I've had a similar issue where I'll open my MacBook and find that it's logged out and none of my Google Calendar events are there.

I dug at this a little bit and chalked this up to the refresh token process failing due to the network being available. I've turned on "Wake for network access" (under System Settings > Battery > Options...) and it happens substantially less. I've also correlated it happening after commuting, where I wouldn't have WiFi nearby.

I do not have concrete proof or logs, just anecdotal evidence. This might help debug why this is happening for others as well?

* This is on MacOS 15.7.2 (24G325)
* MeetingBar v4.11.6

It's been happening for a few months (maybe ever since I moved to my M4). Although I think it's correlated with me unplugging my laptop more.

**Comment by AlexeyRaga** [comment]
I experience the same issue.

**Comment by Volps-deliverThat** [comment]
I am having the same issue

**Comment by Shagon94** [comment]
I've found a working workaround - use the calendar as the source and have the calendar sync every 5-10 mins. MacOS calendar seems to always pull properly.

**Comment by nathanredblur** [comment]
Same issue, In my case I have a terrible annoying Zscaler app that block any request to google when is not active.
So I imagine that meeting bar try to request for calendar events in the midnight or on wake up but computer is sleeping and zscaler VPN is not fully connected, and the request is not successful until zscaler is fully active.

A first initial quick solution could be:
- add a re-fetch button so we not need to remove and add google account every time, just re-try when the VPN is working again.
- add a delay to automatically re-fetch when the computer wake-up

**Comment by leits** [comment]
Hi everyone! Thanks for the reports!

I’ve published a draft V5 release of MeetingBar and would really appreciate help testing it before I mark it as stable.

V5 is a big internal rewrite. It is not only a UI update. A lot of the app’s core logic was rebuilt to make calendar sync, Google Calendar auth, meeting link detection, notifications, fullscreen alerts, onboarding, and preferences more reliable.

The main things I’d love you to test:

* Google Calendar: sign-in, reauthorization, missing calendars, public calendars, events disappearing after sleep/wake
* macOS Calendar: permissions, calendar selection, refresh after changes
* Notifications: normal notifications, fullscreen notifications, auto-join, snooze, dismiss, events without meeting links
* Menu bar: hidden title/icon, long titles, no upcoming events, timeline, dark/light mode, external monitors
* Preferences/onboarding: fresh setup, switching providers, all tabs, localization issues

Some things are intentionally not part of V5 yet: multiple Google accounts, Outlook as a direct provider, attachments/meeting notes, phone number detection, and bigger automation changes.

If you try the draft build, please let me know what works and what breaks. The most useful details are:

* macOS version
* calendar provider: macOS Calendar or Google Calendar
* fresh install or upgrade
* what you tested
* screenshots/logs if something looks wrong

This is a large release, so real-world testing would help a lot before I ship it to everyone. Thank you.
https://github.com/leits/MeetingBar/releases/tag/v5.0.0

<blockquote><img src="https://opengraph.githubassets.com/e7196be5786ca9c218de75adbc969a1c0760ddb7c9d26dc1c35f5016283dc617/leits/MeetingBar/releases/tag/v5.0.0" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/leits/MeetingBar/releases/tag/v5.0.0">Release 5.0.0 (RC) · leits/MeetingBar</a></strong></div><div>MeetingBar V5 — Pre-Release
This is a pre-release build of MeetingBar V5.
V5 is a major internal rewrite focused on making MeetingBar more reliable, predictable, and easier to maintain. It is not j...</div></blockquote>

**Comment by leits** [comment]
@dcc635 @nathanredblur @scottgreenup @Shagon94 @mhasanbulli @davidsandilands @Volps-deliverThat ^

**Comment by sfdye** [comment]
v5.0.0 still crashes after one day 

macOS version: 26.5.1 (25F80)
calendar provider: Google Calendar
fresh install or upgrade: upgrade

**Comment by scottgreenup** [comment]
Hi @leits — 

I think everything looks good for my use case, except maybe fullscreen notifications; but still investigating whether that's a me issue (probably) or not. Here are some notes:

**Google calendar**
- Sign in works, no issues.
- I've had to reauthorise after periods of travel (where laptop would be in bag with no networking).
- No calendars missing for me, they are all under "unknown" though if that matters? This includes "My calendars" and "Other calendars" (the labels from calendar.google.com)
- I haven't noticed events disappearing.

**MacOS calendar**
* I'm not using macOS calendar.

**Notifications**
- I did _miss a couple fullscreen notifications_, but most have come through. I think this might have to do with my window manager, but I'll update you if I find a root cause.
- I'm not using auto-join, snooze, or dismiss.

**Menu bar**
- Every icon and title works.
- Shortening the title works.
- Icons show correctly.

**Preferences**
- I'm in english, no issues.
- I'm not sure if preferences just loaded or not, it seemed to be the same experience as far as I can remember.

**Details**

- MacOS: Sequoia 15.7.7 (24G720)
- Google calendar
- Fresh install (just downloaded the DMG and have both installed, just running 5.0 on it's own)

**Comment by seahindeniz** [comment]
I dug into this against `master` (5.0.0) and `v4.11.6`, cross-checked it with AppAuth's source, and ran a small harness for the refresh pipeline. Sharing findings in case they're useful.

**There isn't one bug.** There are four, and they share a theme: every failure mode on the Google path is unbounded — it either hangs forever or destroys the stored session. Nothing times out, nothing retries with backoff, and nothing reacts to the network coming back. That's why the symptoms look so different across reporters (@mhasanbulli "re-authenticate every day", @scottgreenup "logged out after a commute", @nathanredblur "Zscaler not up yet", OP "stale events until Refresh Sources").

---

### 1. A transient token-refresh failure destroys the saved session

This is the "I have to re-authenticate every day" one, and it's present identically in 4.11.6 and 5.0.0.

`GCEventStore.validAccessToken` checks the token before the error:

```swift
state.performAction { [weak self] accessToken, _, error in
    if let token = accessToken {
        cont.resume(returning: token)   // ← error is dropped
```

But AppAuth, on a **transient** (network) refresh failure, invokes the action with the *previous, already-expired* access token alongside the error — [`OIDAuthState.m`](https://github.com/openid/AppAuth-iOS/blob/master/Sources/AppAuthCore/OIDAuthState.m):

```objc
} else {
  if (error.domain == OIDOAuthTokenErrorDomain) { ... }   // grant rejected
  else { ...didEncounterTransientError... }               // network failure
}
...
actionToProcess.action(self.accessToken, self.idToken, error);
```

`-accessToken` only returns `nil` once `_authorizationError` is set, which a network error does **not** do. So the expired token comes back and the error is thrown away. Then:

1. Expired token → Google returns **401**
2. `GoogleHTTPStatusPolicy.classify` → `.retryWithForcedTokenRefresh`
3. `validAccessToken(forceRefresh: true)` → still offline → **same expired token returned again**
4. Retry → **401** → `retrying == true` → `.clearAuthAndThrowAuthRequired`
5. `clearAuthState()` → `Keychain.delete` → **refresh token gone, full re-consent required**

A laptop that wakes before Wi-Fi or a VPN is up is enough to wipe the OAuth grant. Aggravating detail: `validAccessToken` reuses an in-flight `refreshTask` *before* honoring `forceRefresh`, so step 3 can be served the same stale token from the already-running task.

### 2. Requests never fail — they hang for up to 7 days

```swift
cfg.waitsForConnectivity = true   // and no timeoutIntervalForResource
```

With `waitsForConnectivity`, `timeoutIntervalForRequest` does not apply while waiting; only `timeoutIntervalForResource` does, and that defaults to **604800 s (7 days)**. A fetch started while offline doesn't error, it parks.

This is also the tell for OP's report: in 4.11.6 a *failed* cycle publishes `([], [])`, so the menu would go empty. Seeing **yesterday's events** instead means no cycle ever completed.

### 3. A background refresh can open an OAuth browser tab and await it forever

`ensureSignedIn()` → `signIn()` → `NSWorkspace.shared.open(url)` plus a continuation that only resumes if the user finishes in the browser. If they don't (they're asleep), the fetch never completes — and `signInTask` is never cleared, because its `defer` lives in the suspended `ensureSignedIn`. Every later refresh then does `try await signInTask.value` on a dead task.

### 4. 5.0.0 turned "one hung fetch" into a total refresh deadlock

`CalendarSync.swift` — `flatMap(maxPublishers: .max(1))` around a `Future` that only completes when its async task does. 4.11.6 used unbounded `flatMap`. I ran the exact pipeline shape:

```
=== healthy ===                       === first fetch hangs ===
[0.51s] fetch #1 STARTED              [0.50s] fetch #1 STARTED
[0.56s] fetch #1 DELIVERED            [2.00s] >>> user presses Refresh
...                                   RESULT: started=1 delivered=0
RESULT: started=9 delivered=8
```

A single never-completing fetch kills the 180 s timer, settings-change triggers **and the Refresh button**, for the life of the process. `changeEventStoreProvider` is the only thing that cancels `refreshCycleTask` — which is exactly why "switch to Apple Calendar and back" is the workaround people keep finding. @sfdye's "v5.0.0 still crashes after one day" is consistent with this.

### 5. Contributing: no network-recovery trigger

`grep NWPathMonitor` → nothing. 5.0.0 added wake and day-change refreshes, but wake fires *before* Wi-Fi reassociates or a VPN connects — the worst possible moment given #1 and #2. This is precisely @nathanredblur's request.

---

### Fixes

I have these implemented and can open a PR if it's welcome:

1. In `validAccessToken`, inspect `error` **before** `accessToken`; add a distinct retryable `AuthError.temporarilyUnavailable` for non-`OIDOAuthTokenErrorDomain` failures.
2. Never `clearAuthState()` on an API 401 — only when the token endpoint rejects the refresh token (already reported via `didEncounterAuthorizationError`). A 401 becomes a visible "Reconnect", not a silent sign-out.
3. `waitsForConnectivity = false`, plus explicit `timeoutIntervalForRequest`/`ForResource`, so failures are bounded and the next cycle self-heals.
4. Fetches use a non-interactive session gate; interactive authorization stays with the explicit sign-in path used by provider selection and Reconnect.
5. A timeout around the refresh cycle so the `Future` always completes and `.max(1)` can't deadlock.
6. An `NWPathMonitor` trigger that refreshes on the unreachable → reachable transition.

One caveat: none of this can eliminate a genuine Google-side revocation (user revokes access, or an OAuth client in "Testing" publishing status expiring refresh tokens after 7 days). That legitimately needs re-consent — but it should surface as an actionable Reconnect state rather than silence plus stale data.
